stages:
  - generate
  - deploy

variables:
  GIT_DEPTH: "1"
  POST_DEPTH: 10

generate:
  stage: generate
  tags: 
    - linux
  image: node
  script:
    - apt update ; apt -y install build-essential python3 sqlite3 git
    - git clone --depth=1 https://code.mycard.moe/mycard/ygopro-database
    - npm ci
    - npm run build
    - npm start
  artifacts:
    paths:
      - output

upload_to_minio:
  stage: deploy
  dependencies:
    - generate
  tags: 
    - linux
  image: python
  script:
    - pip install -U awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync --delete output/ s3://mycard/cn-database
  only:
    - master

deploy_to_ygopro_server:
  stage: deploy
  dependencies:
    - generate
  tags:
    - linux
  script:
    - apt update && apt -y install openssh-client rsync coreutils
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan koishi.momobako.com >> ~/.ssh/known_hosts
    - echo $NANAHIRA_SSH_KEY | base64 --decode > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/*
    - scp -r output/cards.cdb nanahira@koishi.momobako.com:~/ygopro-cn/cards.cdb
  only:
    - master
